//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dog()
        {
            this.Comment = new HashSet<Comment>();
            this.Follow = new HashSet<Follow>();
        }
    
        public long idDog { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string kind { get; set; }
        public string figure { get; set; }
        public long sender { get; set; }
        public System.DateTime sendTime { get; set; }
        public Nullable<long> adopter { get; set; }
        public Nullable<System.DateTime> adoptTime { get; set; }
        public int loves { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual DogLover DogLover { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follow { get; set; }
        public virtual DogLover DogLover1 { get; set; }
    }
}
