//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonateRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonateRecord()
        {
            this.DonateItem = new HashSet<DonateItem>();
        }
    
        public long idDonateRecord { get; set; }
        public long lover { get; set; }
        public Nullable<int> items { get; set; }
        public Nullable<int> lovesInc { get; set; }
        public System.DateTime donateTime { get; set; }
    
        public virtual DogLover DogLover { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonateItem> DonateItem { get; set; }
    }
}
