//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonateItem
    {
        public long idDonateItem { get; set; }
        public long record { get; set; }
        public string category { get; set; }
        public string name { get; set; }
        public int number { get; set; }
        public string unit { get; set; }
    
        public virtual DonateRecord DonateRecord { get; set; }
    }
}
