//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public long idActivity { get; set; }
        public string admins { get; set; }
        public string lovers { get; set; }
        public string dogs { get; set; }
        public string kind { get; set; }
        public string desc { get; set; }
        public string images { get; set; }
    }
}
