//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public long idAdmin { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string figure { get; set; }
        public string motto { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string post { get; set; }
        public Nullable<System.DateTime> postTime { get; set; }
    }
}
