//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogLover
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DogLover()
        {
            this.Comment = new HashSet<Comment>();
            this.Dog = new HashSet<Dog>();
            this.Dog1 = new HashSet<Dog>();
            this.DonateRecord = new HashSet<DonateRecord>();
            this.Follow = new HashSet<Follow>();
        }
    
        public long idUser { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string figure { get; set; }
        public int loves { get; set; }
        public int adoptDogs { get; set; }
        public int loveDogs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dog> Dog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dog> Dog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonateRecord> DonateRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follow { get; set; }
    }
}
