//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public long lover_ { get; set; }
        public long dog_ { get; set; }
        public Nullable<System.DateTime> followTime { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual DogLover DogLover { get; set; }
    }
}
