//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdoptedDog
    {
        public long idAdoptedDog { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string kind { get; set; }
        public string figure { get; set; }
        public Nullable<long> sender_ { get; set; }
        public Nullable<long> adopter_ { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public Nullable<System.DateTime> adoptTime { get; set; }
    
        public virtual DogLover DogLover { get; set; }
        public virtual DogLover DogLover1 { get; set; }
    }
}
