//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long idComment { get; set; }
        public Nullable<long> commenter { get; set; }
        public Nullable<long> dog { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> commentTime { get; set; }
    
        public virtual DogLover DogLover { get; set; }
        public virtual Dog Dog1 { get; set; }
    }
}
