//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dog_stationEntities : DbContext
    {
        public dog_stationEntities()
            : base("name=dog_stationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<AdoptedDog> AdoptedDog { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Dog> Dog { get; set; }
        public virtual DbSet<DogLover> DogLover { get; set; }
        public virtual DbSet<DonateItem> DonateItem { get; set; }
        public virtual DbSet<DonateRecord> DonateRecord { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
    }
}
