//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long idInventory { get; set; }
        public string category { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public Nullable<int> quantity { get; set; }
        public string unit { get; set; }
    }
}
